Repository bgantzler/ember-mirage, pull requests merged in 2024-11, with the labels that each got.

#43 Update migration docs with path cleanup, latest on progress
  docs/migration.md
Labels: documentation

#45 Update base workflows and lockfile for pnpm 9, set `packageManager`
  .github/workflows/ci.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .github/workflows/push-dist.yml
  .npmrc
  ember-mirage/package.json
  package.json
  pnpm-lock.yaml
  test-app/config/ember-try.js
  test-app/package.json
Labels: internal

#44 Widen peer range for miragejs
  ember-mirage/package.json
Labels: bug

#47 Explicitly define a wide peer range to include alpha releases of miragejs
  ember-mirage/package.json
Labels: bug
